[package]
name = "p_set4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.0"
plotters = "0.3.3"
rand = {version = "^0.8.4", features = [ "small_rng" ]}
rayon = "1.7.0"
